### PR TITLE
AppBar Stuff

### PR DESCRIPTION
**Pull request by allie-rae**

### CODE REVIEW

**Comment by jae-finger** [comment]
:D

**Review by squashgray — APPROVED** [review]

**Review by zimashima — APPROVED** [review]
I see refactoring opportunity for DrawerAppBar :) Maybe we can create an issue for this one XDezsaw3

**Review by jae-finger — APPROVED** [review]

**Review by danimal-johnson — APPROVED** [review]
Looks good.

**Comment by jae-finger** [comment]
Great job!

**Pull request merged**
