### PR TITLE
prettier setup

### PR DESCRIPTION
**Pull request by squashgray**

### CODE REVIEW

**Review by allie-rae — APPROVED** [review]
hells to the yeah!!!

**Review by allie-rae — APPROVED** [review]
🥳 🥳 🥳

**Review by zimashima — APPROVED** [review]
LGTM~ P.S. We all need to watch @allie-rae from changing ``semi: true`` to ``semi:false`` from now on...

**Review by danimal-johnson — APPROVED** [review]
Thanks for the semicolons! Looks good!

**Comment by jae-finger** [comment]
.

**Pull request merged**
